### ISSUE TITLE
Console for the HLF without system channel

### ISSUE THREAD

**Issue by trafoDev** [hyperledger-labs/fabric-operations-console#116]
I'm trying to set up a console for the HLF 2.4.1 no system channel. I have a simple network with two orgs, one peer, CA, and orderer each. I have two channels with both orgs (peer & orderer). I'm wondering if the Console is supporting networks as such?

I successfully added orgs and CAs to the Console. From the peer's perspective, I can see chaincodes installed bun no channels.

![console0](https://user-images.githubusercontent.com/47941216/149401977-a37eb823-3154-43ce-8104-bee70a5e3c76.png)

The real problem is when I'm trying to configure orderers. I tried to configure proxy for one ordered, but I was unable to connect with the Admin certs from org MSP.

![console1](https://user-images.githubusercontent.com/47941216/149403214-62278256-122a-4ac5-86d0-4cf3e695cb95.png)

I haven't found anything in the documentation about configuring Console for no system channel networks (system channel is marked as deprecated starting from 2.4.0), so it seems there is no support for this yet. If I'm right, it should be added in the nearest future.

**Comment by varadgit** [comment]
@trafoDev Thanks for opening this requirement. Yes, console does not support this feature yet. We are in the process of evaluating priorities and this is one of the ones in the top.

**Comment by varadgit** [comment]
This is complete
