### ISSUE TITLE
Does 503(import_only_enabled,api is not available) cause "Unable to connect to peer/orderer"

### ISSUE THREAD

**Issue by uqix** [hyperledger-labs/fabric-operations-console#190]
<img width="1785" alt="image" src="https://user-images.githubusercontent.com/10142314/164885411-da155835-4483-4622-9bad-da83bea83a7f.png">

**Comment by varadgit** [comment]
@uqix That log message is noise we need to fix... that happens because there is some logic that connects to the deployer/operator that's not part of the open source and it is trying to connect to it...

the message you are seeing I believe is because of connectivity issues... perhaps grpc proxy is not setup in front of the peer? You could also look at the network traffic to see if there are not errors and pending requests.

**Comment by uqix** [comment]
But the __Channels__ page works just fine, does it mean the connectivity is ok?

<img width="1633" alt="image" src="https://user-images.githubusercontent.com/10142314/165108360-a5156d20-73a4-41a0-9287-63c3a74dc17a.png">

**Comment by varadgit** [comment]
Thanks for the datapoint... that helps... The fact that the version is populated generally means the operations endpoint is functional and the fact that you are able to see the channel means the grpc endpoint is functional.

Do you have more than one peer? If so, can you switch to the different peers and see if there is a difference?

I just setup a test network using the script and I am able to view the peer page
![image](https://user-images.githubusercontent.com/1103650/165133888-8a3eed71-cf81-445c-8243-c3ff62907216.png)

couple of things to check...
1. In Network tab, clear the content and visit the peer page and see what the request, response are. Any errors with deployer should be generally fine. I suspect we will see some failing request or pending request that might help.
FYI... I have these errors (that are benign) 
![image](https://user-images.githubusercontent.com/1103650/165135124-a8c13356-2f1f-425e-9aa6-e961f6346586.png)

2.  In the console tab see if there are any other errors

**Comment by uqix** [comment]
This is a little weird, the `Peer` page finally show details after waiting long enough, while the error message still exists:

<img width="1768" alt="image" src="https://user-images.githubusercontent.com/10142314/165721713-3625804c-98d3-493d-b782-c80cb4e026c2.png">

**Comment by varadgit** [comment]
weird, indeed! 

That message comes from the health check... if the healthcheck endpoint didn't respond in 30 seconds that message gets displayed.

Can you check this URL?
`<peer_operations_url>/healthz`

**Comment by uqix** [comment]
@varadgit 
<img width="1788" alt="image" src="https://user-images.githubusercontent.com/10142314/167329101-ae5a1f6c-0fa7-4d6a-95fc-0fb2dc25b1d2.png">

> failed to ping to Docker daemon: cannot connect to Docker endpoint

But we use ccaas instead of Docker.

**Comment by varadgit** [comment]
@uqix This is because of this following line
https://github.com/hyperledger/fabric/blob/release-2.2/sampleconfig/core.yaml#L484

Can you try commenting that out and see if that helps?

**Comment by varadgit** [comment]
You might want to open an issue and see how to configure it... Basically, the health endpoint relies on that setting and the Fabric default doesn't quite work for non-docker env.

**Comment by uqix** [comment]
I commented out `endpoint: unix:///var/run/docker.sock` in  peer `/etc/hyperledger/fabric/core.yaml`, same error:

"failed to ping to Docker daemon: cannot connect to Docker endpoint"

**Comment by uqix** [comment]
<img width="607" alt="image" src="https://user-images.githubusercontent.com/10142314/168237276-826e872b-5d4c-44fc-b228-56d91d9a9d81.png">

All those ajax calls finished in less than 2 secs, why are the console waiting for so long?

**Comment by varadgit** [comment]
@uqix Can you post the specific call that took time? Is it the call to get the list of components?

**Comment by uqix** [comment]
> I commented out `endpoint: unix:///var/run/docker.sock` in peer `/etc/hyperledger/fabric/core.yaml`, same error:
> 
> "failed to ping to Docker daemon: cannot connect to Docker endpoint"

My bad, was not aware the env var `CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock` is passed by bevel to peer, removing it fixes this issue.

Thanks for your time.
