### ISSUE TITLE
Transaction Output doesn't display utf-8 chars correctly

### ISSUE THREAD

**Issue by uqix** [hyperledger-labs/fabric-operations-console#198]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/10142314/166892641-861d3b0a-f8dd-4306-b59e-57aabffe46b2.png">

**Comment by uqix** [comment]
As you can see, key in Output displays correctly, but value does not(e.g. `province` field)

**Comment by uqix** [comment]
Hey, guys, we really need this sorted out.

**Comment by varadgit** [comment]
@dshuffma-ibm Is this possible?

**Comment by dshuffma-ibm** [comment]
alrighty, I decided to do this real quick after all.

once https://github.com/hyperledger-labs/fabric-operations-console/pull/210 is merged you should be good.

**Comment by uqix** [comment]
I will test it once merged.

**Comment by uqix** [comment]
<img width="513" alt="image" src="https://user-images.githubusercontent.com/10142314/169428024-521885dc-ae9f-4d2a-9cd3-23fe8a538a5b.png">

Input still has the problem.

**Comment by dshuffma-ibm** [comment]
thanks for testing it @uqix

**Comment by uqix** [comment]
Tested and all fixed.
