### ISSUE TITLE
Create or update channel not possible

### ISSUE THREAD

**Issue by aMinuteMan** [hyperledger-labs/fabric-operations-console#202]
Hello,

I am trying to use the fabric operation console with an existing network and I am facing some problems while updating or creating channels.

My setup:
- 1 organization with CA and 3 peers
- 1 orderer organization with CA and 3 orderers
- 1 channel created via configtxgen/peer commands on the command line

All nodes are running fine as far as I can tell and the channel has been created successfully and all peers have joined the channel

Now I have added the console to the deployment and performed these steps:

1. create assets based on your example script
2. bulk import to the console
3. associated the identities based on your readme

So far everything looks fine, all nodes are connected and I can see the previously created channel in the channels tab.

Now I am seeing 2 issues. They might have the same root cause so I put them here both:

**Issue 1 - Modify existing channel**
1. Go to "Channels" and click on the previously created channel.
2. Click on the "settings" icon

Here the "Select the MSP" dropdown list is empty. There is no information in the logs (server or client).

**Issue 2 - Create new channel**
1. Go to "Channels" and click "Create Channel"
2. Select "Advanced channel configuration" and next
3. Type in channel name, select orderer from dropdown list and next
4. Add the MSP (here it is visible in the dropdown list) as operator and next
5. Use "1 out of 1" policy and next
6. Select MSP and its admin identity and next
7. Choose "2.0.0" for application and orderer capabilities
8. Then use defaults and choose orderer MSP
9. Review and create the channel
10. From the notifications, select the orderer MSP admin and approve

Now I see the following error: "**Signature failed. unauthorized - untrusted signature (scs)**"

In the logs I can see this:

server log:
```
silly: [auth sig collection] checking scs against hash: 64 93a43c1112abef9658dd9a68aa5fe71fb5ee78da7113865d0df2f80640de31d5
info: [auth sig collection] scs on hash is valid. step:[1/2] orderer-masterMSP
error: [auth sig collection] cert that created scs is not trusted by any known root certs. sig not trusted. msp: orderer-masterMSP
debug: [auth sig collection] number of trusted certs for msp: 1 msp: orderer-masterMSP
```
client log:
```
[error] signatureDetailModal:{\n    "statusCode": 401,\n    "msg": "unauthorized - untrusted signature (scs)"\n}
```

I don't know how to proceed. e.g. could this be an issue with the assets used for the import, or is this an indication that something is wrong with my network setup itself?

Any help would be very much appreciated!

**Comment by varadgit** [comment]
I believe this PR fixed it... can you pull the latest console image and try?
https://github.com/hyperledger-labs/fabric-operations-console/pull/192

**Comment by aMinuteMan** [comment]
Hello varadgit,

true, https://github.com/hyperledger-labs/fabric-operations-console/pull/192 is related as far as I can tell. Before I saw a similar error when clicking on "Create channel". 
![image](https://user-images.githubusercontent.com/105093268/167771320-8ae92a58-8376-4ea7-99ef-6b91fb0f2fdc.png)

After https://github.com/hyperledger-labs/fabric-operations-console/pull/192 I can click create channel, see the notification and see the error when signing as the orderer MSP.
![image](https://user-images.githubusercontent.com/105093268/167771381-20cd44d9-1642-463e-820d-bdfab41fd4a9.png)

Tested with the image published 3hours ago.

**Comment by aMinuteMan** [comment]
Hello @varadgit,

what could be a possible root cause for the empty drop down list in Issue 1, e.g. why would the mapping between the channel information and imported organization (I am guessing here) fail?

Same for issue 2, I am guessing that also here some mapping between the imported data and the data on the blockchain fails for some reason.

Would be great if you could point me to a direction for me to check.

**Comment by varadgit** [comment]
@aMinuteMan 

I tried this scenario on our local setup and it seems to work.

The mapping is done generally by looking at the root certs between the MSP and the channel (and the root cert for orderers/peers)

I would check the channel root certs and compare it with the root cert of the imported orderer (and member) MSP.

If you are using docker, you might want to clear the storage for couchdb which will clear components and you can start fresh... you can also delete each component and MSP to make sure you are using the correct one... also make sure to remove the old wallet identities and get a new one appropriate for the network.

**Comment by varadgit** [comment]
1. We do get the certs using Fabric CA as part of the script like here - https://github.com/hyperledger-labs/fabric-operations-console/blob/main/scripts/createAssets.sh#L30-L31
2. Are you saying you imported the CA, created a new MSP from the UI and it did not work when you use it to sign? 
3. Generally, we recommend using our UI to create/modify channels and we don't have a lot of tests for modifying channels created outside the UI since we can't control all the variability and have a reliable way to parse. But if you can open up a separate issue we can take a look.
4. Channel permissions: I think this is related to the previous bullet. If the channel was created outside the UI, it is harder to parse it in a reliable way. I am thinking this is a result of something we don't understand in the channel policy. If you are creating channels outside the UI, you might want to create one from the UI, get the channel config and use that as a template so that the UI has a better chance of understanding.

**Comment by aMinuteMan** [comment]
1. I was using this too in the beginning with the outcome described above. e.g. If I retrieve the cert from the console via `https://localhost:9054/cainfo` and run `base64 --decode` there is no newline at the end. But if I run `cat cert.pem | base64 -w 0` and again decode via `base64 --decode` there is a newline. The difference of the encoded certs is for example like this at the end:
- via `https://localhost:9054/cainfo`: LS0tLS1CR1lEVlFRSj.......NJZ3FCcVFhFLS0tLS0=
- via `cat cert.pem | base64 -w 0`: LS0tLS1CR1lEVlFRSj.......NJZ3FCcVFhFLS0tLS0**K**

I would consider this as clarified for me since following the IBM documentation works fine for me. I don't see any follow up action here.

2. The opposite, so creating the same MSP in the UI works just fine, as well as creating the asset json file via `cat cert.pem`

3. Once I have time I will create channels both ways and report back the differences in the channel config.

4. Understood!

If you agree we can close this topic. From my side it is clarified and I am not blocked anymore.

Again, thanks a lot Varad!

**Comment by varadgit** [comment]
cool! I am glad it is resolved...
