### ISSUE TITLE
Roadmap for operations console development

### ISSUE THREAD

**Issue by aMinuteMan** [hyperledger-labs/fabric-operations-console#221]
Hello,

from going through the issues I understood that you are currently in the process of setting up priorities for upcoming changes, resp. working on a roadmap.

Is this still a working in progress or do you have already a roadmap which you could publish?

I would find it really helpful to have an idea where the development of the console is heading.

**Comment by dshuffma-ibm** [comment]
@aMinuteMan the short-term road map is to add console support for **Fabric system-less channel features.** So specifically this is to:
- create orderers that do not use a system channel (requires deployer)
- add support to create/edit/view channels using the Fabric channel participation features
- add support to join orderers to application channels
- add support for orderers to "unjoin" application channels (aka leave a channel)

**Comment by aMinuteMan** [comment]
@dshuffma-ibm Got it, thank you!
