### ISSUE TITLE
[Session Requests] exceeded the high volume rate limit

### ISSUE THREAD

**Issue by aMinuteMan** [hyperledger-labs/fabric-operations-console#266]
Hello,

I am seeing this message time by time when navigating through the UI, e.g.

1. Open channels and open one specific channel
2. Switch to channel details
 ==> Message about connection problems with peer pops up on the right top side.
 ==> Refresh and the above message shows up
![image](https://user-images.githubusercontent.com/105093268/179931817-4f447a5e-0c61-48f3-aaf2-09e0585b9738.png)
3. Wait a minute and try again
 ==> everything works fine

I have the feeling that this happens more often when I navigate to quickly though the UI.

What is the meaning behind this error and is there a way to work around it?

**Comment by varadgit** [comment]
@aMinuteMan It is controlled by the following two variables that can be overridden in the config

https://github.com/hyperledger-labs/fabric-operations-console/blob/main/packages/athena/json_docs/default_settings_doc.json#L160-L161

description - https://github.com/hyperledger-labs/fabric-operations-console/blob/ba3c7156888dfd41e813ea8d1d4c864f89a77e5c/packages/athena/json_docs/json_validation/ibp_openapi_v3.yaml#L13981

**Comment by aMinuteMan** [comment]
Thanks @varadgit !
