### ISSUE TITLE
how the console actually work with a running fabric network

### ISSUE THREAD

**Issue by litong01** [hyperledger-labs/fabric-operations-console#29]
Need a bit document talking about how this app works with a running fabric network. where does it find endpoints of various nodes, channels, certificates.

**Comment by shubham-edx** [comment]
+1

**Comment by varadgit** [comment]
We should have the following pieces to documented... @litong01 @shubham-edx would these help?
1. Architecture diagram on how things flow between browser to grpc-web, peer/orderer
2. How to find pieces to construct JSON file for import from an existing fabric?

**Comment by litong01** [comment]
Thanks for the pointers. Will close this.

**Comment by shubham-edx** [comment]
Hey @varadgit ,
Thanks for responding. Yes, these two points would definitely help.

**Comment by varadgit** [comment]
one part of this (architecture diagram) is addressed here
https://github.com/hyperledger-labs/fabric-operations-console/pull/40

**Comment by dshuffma-ibm** [comment]
So I think the next part can be addressed by reading the swagger/open api file we have. The details for what is needed for an import is broken down by component with details. Its all in this JSON. 
- https://github.com/hyperledger-labs/fabric-operations-console/blob/main/packages/athena/json_docs/json_validation/ibp_openapi_v3.yaml


I'd recommend pasting it into https://editor.swagger.io/ and jumping to the `Import a ca`, `Import a peer`, and `Import an ordering service` sections. Once you click an API, click the `Schema` text to see the descriptions of each field.

closing, feel free to re-open if your question wasn't addressed.
