### ISSUE TITLE
Can't get deatils of orderer_local after restart of test-network and operations console 

### ISSUE THREAD

**Issue by turantk** [hyperledger-labs/fabric-operations-console#322]
First run and associating identities are ok but when I stop everything and open them again I can’not reach details

1- I start test-network and console using the commands;
	      **_./setupNerwork.sh up
	      ./setupConsole.sh up_**

2- I create assets using the command;
 	      **_./createAsset.sh_**

![image](https://user-images.githubusercontent.com/115465761/194848873-7ac65a34-364a-4ea5-a3ad-e86e21c62d36.png)

3- I login http://localhost:3000/ , import assets and save 

4- I associated  all identities and displayed details successfully

![image](https://user-images.githubusercontent.com/115465761/194849014-2dd4c997-3ba3-469e-84b9-5d073413f1d6.png)

5- I logout the console and stop  both console and test-network
	      **_./setupConsole.sh down
	      ./setupNetwork.sh down_**

6- I start the  test-network and console again using the following commands;
	~/fabric-operations-console/fabric-samples/test-network$ ./network.sh up -ca -s couchdb
  **or**  ./setupNetwork.sh up

	./setupConsole.sh up

7- I get the following error when I open orderer_local details;

**_“Unable to get channel information from orderer_local. The associated identity does not have administrative privilege. Ensure that the associated identity has administrative privilege.”_**
 
![image](https://user-images.githubusercontent.com/115465761/194849089-9719ed31-af5f-4c4b-8517-ff59a6c32959.png)

8- For ordererca-local,  I also get error saying **_“Unable to retrieve the list of users”_**
 
![image](https://user-images.githubusercontent.com/115465761/194849126-4387cbf2-fdab-442c-ac33-4c333e056ed1.png)

**Comment by turantk** [comment]
@varadgit  Any idea?

**Comment by varadgit** [comment]
@turantk when you "down" and "up", it is going to create new containers and new certificates. You will need to redo the `./createAsset.sh`, clear identities from wallet in browser and create new ones and associate with components.

**Comment by turantk** [comment]
@varadgit  Thank you very much for your answer. I would like to say that you doing a great job.

**Comment by varadgit** [comment]
closing
