### ISSUE TITLE
Failed to register CA identity 

### ISSUE THREAD

**Issue by bjwswang** [hyperledger-labs/fabric-operations-console#332]
Error log: 

![image](https://user-images.githubusercontent.com/30621793/198181438-f03f5dae-c972-466f-8604-3ba8c35388c1.png)

CA error log
![image](https://user-images.githubusercontent.com/30621793/198181597-1cc86885-da06-4ff5-9349-71d4a83d0626.png)

**Comment by dshuffma-ibm** [comment]
The title of this issue mentions `register` but the screen shot shows the `enrolling/associating` process.  The error indicates that the enroll ID you are trying does not exist. So i'd guess you had a problem registering the id in the first place.

If this the first time using this CA, you will need to enroll the "root" id before you can register other ids. This "root" id is the enroll id/enroll secret that you entered when you created the CA. This id is somewhat special b/c its the first one, and it will have rights to create (register) more IDs.

**Comment by dshuffma-ibm** [comment]
closing, inactivity
