### ISSUE TITLE
console error on deployer API endpoint

### ISSUE THREAD

**Issue by litong01** [hyperledger-labs/fabric-operations-console#34]
The browser console keeps showing error messages accessing the deployer api which is not good. I think that the project should only access the deploy api (using POST) method to create new nodes based on a flag (such as DEPLOYER_ENABLED=yes or no). This should not be removed, rather only access it if deployer is enabled.

**Comment by litong01** [comment]
The configurable deploy api should include fqdn so that the deploy service is separate from console.

**Comment by litong01** [comment]
The body of the request should be very well defined so that the implementation can be compatible cross different implementations.

**Comment by dshuffma-ibm** [comment]
Hmm this already exist, the flag `import_only_enabled` is set in the default settings. 
- https://github.com/hyperledger-labs/fabric-operations-console/blob/main/packages/athena/json_docs/default_settings_doc.json#L109

This disables the deployer calls, however it will log a `warning` for the deployer calls. 
- https://github.com/hyperledger-labs/fabric-operations-console/blob/main/packages/athena/libs/deployer_lib.js#L872

Can you post an example?

**Comment by dshuffma-ibm** [comment]
closing, inactivity
