### ISSUE TITLE
Console not loading on Local host

### ISSUE THREAD

**Issue by couchmeka** [hyperledger-labs/fabric-operations-console#348]
I installed using Windows 2022 server. I didn't get any errors but when I browse to local host on edge or chrome, I am not able to see a console. I followed the steps on the read me and I didn't see anything else I should have done. I do have IIS on the local host machine so I can see that it is running just nothing on port 3000.

**Comment by dshuffma-ibm** [comment]
Well i'm a little confused, if you followed our readme why is IIS involve, what role did you want IIS to play here? Fabric operations console has it's own webserver (node.js + express). Where you able to use our scripts on the reademe to start a [network](https://github.com/hyperledger-labs/fabric-operations-console#bring-up-a-fabric-223-network) and the [console](https://github.com/hyperledger-labs/fabric-operations-console#bring-up-console)? Does `docker ps` show several containers running?

**Comment by couchmeka** [comment]
It ended up being the port used to deploy but I got it up thank you! ![image](https://user-images.githubusercontent.com/21232416/210451896-2c287208-9740-4b2c-b32f-243f680939b5.jpeg)

**Comment by dshuffma-ibm** [comment]
cool!
