### ISSUE TITLE
the console can not use a different custom password

### ISSUE THREAD

**Issue by litong01** [hyperledger-labs/fabric-operations-console#35]
when use DEFAULT_USER_PASSWORD_INITIAL and DEFAULT_USER_PASSWORD to setup a password which is not the word 'password', the user cannot use the custom password to login nor the original default `password` to log in.

**Comment by dshuffma-ibm** [comment]
@litong01 this works on my end, I think the issue might be the missing a restart? So on startup it sets the password. If you were already running  and then change the `DEFAULT_USER_PASSWORD_INITIAL` , it will not do what you want.

So could you restart the web server before trying again.

I've updated the docs around these confusing fields: https://github.com/hyperledger-labs/fabric-operations-console/pull/77

**Comment by dshuffma-ibm** [comment]
oh also if you are setting this in the config yaml file, it should be lowercase `default_user_password_initial`

**Comment by dshuffma-ibm** [comment]
closing, inactivity
