### ISSUE TITLE
Remote Ops Console api timeout

### ISSUE THREAD

**Issue by demianko** [hyperledger-labs/fabric-operations-console#353]
I have set up an operations console in aws and imported assets.

when trying to perform "associate identity" on the remote ops console, I received "The certificate could not be generated." error.

in the browser network log, I noticed there are "408 Request Timeout" errors on the remote ops console, http://{{aws host ip}}:3000/api/v2/proxy/ when I was on "associate identity" screen.

Compared to the my local ops console, i don't see any "request timeout" error on the proxy api. but I do see multiple of them when accessing remote ops console in aws.

![image](https://user-images.githubusercontent.com/13011315/211206078-1ff7fa09-9441-4c3b-9d8e-3322c3c6e226.png)

is there any additional configuration I need to do for the remote ops console in order to prevent this type of timeout?

**Comment by dshuffma-ibm** [comment]
@demianko the `/proxy` route can be a bit confusing to debug. its purpose is to allow the browser to ask the console server to contact a node (ca, orderer, or peer). it could be the browser was unable to contact the console, or it could be the console server was unable to contact the node. considering other `/proxy` routes returned, its likely that its the 2nd case. to figure out where that proxy route is going, you can open the body of the request. 

once you know where it= is going, you can try to work out why the console server is unable to contact it. maybe that node is down, maybe there's a firewall preventing it, maybe its going to the wrongly entered address, etc.

**Comment by demianko** [comment]
thanks for the pointer.
the issue was one of the operation url port (10954) was not open in aws ec2 security group.
with the port open, the error (408 request timeout) is resolved.

the only port my local browser interacts with the console server is 3000 in config.yaml configuration, i am curious how the closed port in the server in ec2 is affecting the UI.

**Comment by dshuffma-ibm** [comment]
closing, inactivity
