### ISSUE TITLE
setting up ops console with https

### ISSUE THREAD

**Issue by demianko** [hyperledger-labs/fabric-operations-console#354]
Need help on setting up Ops console with https in order avoid "crypto.subtle" error.

following https://github.com/hyperledger-labs/fabric-operations-console/issues/160 issue, I am setting up host_url with https, but not successful.

https://github.com/hyperledger-labs/fabric-operations-console/blob/main/docker/console/env/config.yaml#L7

I changed "host_url:https://{{ip.address}}" and "app_port:3000" in config.yaml, but didn't work.
i am able to access the login page using "http://{{ip.address}}:3000", but not accessible with https://{{ip.address}}.
On "http://{{ip.address}}:3000", once I login with admin/default password, it fails to load the following page.

on the 2nd attemps, I changed "host_url:https://{{ip.address}}" and "app_port:443", but this didn't work either.
i am not able to access the login page at all.

note: port 443 is open in the firewall (aws ec2 security group)

any help would be appreciated.

**Comment by dshuffma-ibm** [comment]
closing, inactivity
