### ISSUE TITLE
Unable to Create Certificate Authority: Namespace Not Found

### ISSUE THREAD

**Issue by phinow** [hyperledger-labs/fabric-operations-console#514]
Description:
I encountered an issue while attempting to create a Certificate Authority (CA) on the IBM Blockchain Platform. Unfortunately, I received the following error message during the process:

Error Message: REQUEST_ERROR_IN_RESPONSE: POST /api/saas/v3/components failed with 404: namespaces "n37ef77" not found

I believe this error occurred because the specified namespace "n37ef77" could not be found in the system. As a result, I am unable to proceed with the creation of the CA.

I have ensured that I provided the correct namespace information in my request, but it seems to be missing from the system. This error prevents me from successfully setting up the necessary security and authentication mechanisms for my blockchain network.

I kindly request assistance in resolving this issue. It would be greatly appreciated if the team could investigate and provide guidance on how to create the necessary namespace or resolve any potential configuration issues.

Thank you for your attention to this matter, and I look forward to your prompt assistance in resolving this issue.

Best regards,
Phinow
![namespace_error](https://github.com/hyperledger-labs/fabric-operations-console/assets/29484235/b9a5643e-9f1a-48d4-a6f4-973016f2f858)

**Comment by dshuffma-ibm** [comment]
support for IBM Blockchain Platform is done via support tickets in IBM cloud, this repo (and the github issues) works for opensource users of hyperledger fabric operations console. I think you can start a ticket from here: https://cloud.ibm.com/unifiedsupport/supportcenter
