### ISSUE TITLE
Unable to Migrate to Hyperledger Fabric

### ISSUE THREAD

**Issue by Louie74** [hyperledger-labs/fabric-operations-console#517]
Hello,

I keep getting the message to contact support when I try to migrate our Blockchain to Hyperledger...

Thoughts?

**Comment by dshuffma-ibm** [comment]
sounds like you are on IBP, support for IBM Blockchain Platform is done via support tickets in IBM cloud, this repo (and the github issues) works for opensource users of hyperledger fabric operations console. I think you can start a ticket from here: https://cloud.ibm.com/unifiedsupport/supportcenter
