### ISSUE TITLE
Cannot Associate identity with admin/adminpw

### ISSUE THREAD

**Issue by KanakSasak** [hyperledger-labs/fabric-operations-console#70]
![Screen Shot 2021-10-29 at 22 01 38](https://user-images.githubusercontent.com/19529908/139448884-706b22a7-575b-4b3a-a6fd-91b0dd165abb.png)

I cannot create an associate identity with admin/adminpw like the instruction, any advice?

**Comment by dshuffma-ibm** [comment]
check out the new doc on crypto errors: https://github.com/hyperledger-labs/fabric-operations-console/blob/main/FAQ.md#error-help
